import type {
  Equipment,
  Customer,
  Supplier,
  Rental,
  DamageRecord,
  PartReplacement,
  Maintenance,
  InventoryCheck,
  InventoryItem,
} from '../types';

const now = new Date();
const pastDate = (days: number) => {
  const d = new Date(now);
  d.setDate(d.getDate() - days);
  return d.toISOString();
};

export const mockSuppliers: Supplier[] = [
  {
    id: 'sup-001',
    name: '山野户外用品有限公司',
    contact: '张经理',
    phone: '13800138001',
    address: '杭州市余杭区良渚街道',
    createdAt: pastDate(180),
  },
  {
    id: 'sup-002',
    name: '探险者装备科技',
    contact: '李总',
    phone: '13900139002',
    address: '宁波市鄞州区',
    createdAt: pastDate(150),
  },
  {
    id: 'sup-003',
    name: '自然风露营装备',
    contact: '王经理',
    phone: '13700137003',
    address: '温州市鹿城区',
    createdAt: pastDate(120),
  },
];

export const mockEquipments: Equipment[] = [
  {
    id: 'eq-001',
    name: '三人双层帐篷',
    category: '帐篷',
    brand: 'Naturehike',
    model: 'CloudUp 3',
    purchasePrice: 899,
    purchaseDate: pastDate(200).split('T')[0],
    status: 'available',
    location: 'A区-01货架',
    usageCount: 15,
    supplierId: 'sup-001',
    notes: '防风防雨，适合3-4人使用',
    createdAt: pastDate(200),
    updatedAt: pastDate(5),
  },
  {
    id: 'eq-002',
    name: '羽绒睡袋',
    category: '睡袋',
    brand: '黑冰',
    model: 'B1000',
    purchasePrice: 659,
    purchaseDate: pastDate(180).split('T')[0],
    status: 'rented',
    location: 'B区-02货架',
    usageCount: 23,
    supplierId: 'sup-002',
    notes: '舒适温度-10℃，填充白鸭绒',
    createdAt: pastDate(180),
    updatedAt: pastDate(2),
  },
  {
    id: 'eq-003',
    name: '自动充气防潮垫',
    category: '防潮垫',
    brand: '挪客',
    model: 'NH15Q001',
    purchasePrice: 299,
    purchaseDate: pastDate(160).split('T')[0],
    status: 'available',
    location: 'B区-05货架',
    usageCount: 31,
    supplierId: 'sup-001',
    notes: '厚度5cm，自动充气',
    createdAt: pastDate(160),
    updatedAt: pastDate(10),
  },
  {
    id: 'eq-004',
    name: '60L登山包',
    category: '登山包',
    brand: 'Osprey',
    model: 'Kestrel 60',
    purchasePrice: 1299,
    purchaseDate: pastDate(140).split('T')[0],
    status: 'maintenance',
    location: 'C区-03货架',
    usageCount: 18,
    supplierId: 'sup-003',
    notes: '背负系统舒适，大容量',
    createdAt: pastDate(140),
    updatedAt: pastDate(1),
  },
  {
    id: 'eq-005',
    name: '碳纤维登山杖',
    category: '登山杖',
    brand: '开拓者',
    model: '碳纤维T柄',
    purchasePrice: 199,
    purchaseDate: pastDate(120).split('T')[0],
    status: 'available',
    location: 'D区-01货架',
    usageCount: 42,
    supplierId: 'sup-002',
    notes: '超轻碳纤维，三节可调',
    createdAt: pastDate(120),
    updatedAt: pastDate(7),
  },
  {
    id: 'eq-006',
    name: '便携卡式炉',
    category: '炉具',
    brand: '岩谷',
    model: 'CB-AS-1',
    purchasePrice: 259,
    purchaseDate: pastDate(100).split('T')[0],
    status: 'available',
    location: 'E区-02货架',
    usageCount: 27,
    supplierId: 'sup-001',
    notes: '防风设计，2.9kW火力',
    createdAt: pastDate(100),
    updatedAt: pastDate(3),
  },
  {
    id: 'eq-007',
    name: 'LED露营灯',
    category: '灯具',
    brand: 'Goal Zero',
    model: 'Lighthouse Micro',
    purchasePrice: 229,
    purchaseDate: pastDate(90).split('T')[0],
    status: 'damaged',
    location: '维修区',
    usageCount: 35,
    supplierId: 'sup-003',
    notes: 'USB充电，多档亮度',
    createdAt: pastDate(90),
    updatedAt: pastDate(1),
  },
  {
    id: 'eq-008',
    name: '蛋卷桌',
    category: '桌椅',
    brand: '挪客',
    model: 'NH20JJ007',
    purchasePrice: 399,
    purchaseDate: pastDate(80).split('T')[0],
    status: 'available',
    location: 'F区-01货架',
    usageCount: 19,
    supplierId: 'sup-002',
    notes: '榉木材质，折叠收纳',
    createdAt: pastDate(80),
    updatedAt: pastDate(4),
  },
  {
    id: 'eq-009',
    name: '六角天幕',
    category: '天幕',
    brand: '牧高笛',
    model: 'NXVQU61001',
    purchasePrice: 599,
    purchaseDate: pastDate(70).split('T')[0],
    status: 'rented',
    location: 'G区-02货架',
    usageCount: 12,
    supplierId: 'sup-001',
    notes: '银胶涂层，防晒防雨',
    createdAt: pastDate(70),
    updatedAt: pastDate(2),
  },
  {
    id: 'eq-010',
    name: '折叠月亮椅',
    category: '桌椅',
    brand: '牧高笛',
    model: 'NX23665005',
    purchasePrice: 269,
    purchaseDate: pastDate(60).split('T')[0],
    status: 'available',
    location: 'F区-03货架',
    usageCount: 28,
    supplierId: 'sup-003',
    notes: '人体工学设计，快速折叠',
    createdAt: pastDate(60),
    updatedAt: pastDate(5),
  },
];

export const mockCustomers: Customer[] = [
  {
    id: 'cus-001',
    name: '陈小明',
    phone: '13812345678',
    idCard: '330100199001011234',
    address: '杭州市西湖区',
    rentalCount: 5,
    createdAt: pastDate(150),
  },
  {
    id: 'cus-002',
    name: '李雪梅',
    phone: '13923456789',
    idCard: '330200199203152345',
    address: '杭州市拱墅区',
    rentalCount: 3,
    createdAt: pastDate(120),
  },
  {
    id: 'cus-003',
    name: '王大伟',
    phone: '13734567890',
    idCard: '330300198805203456',
    address: '杭州市余杭区',
    rentalCount: 8,
    createdAt: pastDate(100),
  },
  {
    id: 'cus-004',
    name: '张晓燕',
    phone: '13645678901',
    idCard: '330400199508084567',
    address: '杭州市滨江区',
    rentalCount: 2,
    createdAt: pastDate(80),
  },
  {
    id: 'cus-005',
    name: '刘强',
    phone: '13556789012',
    idCard: '330500198712125678',
    address: '杭州市萧山区',
    rentalCount: 6,
    createdAt: pastDate(60),
  },
];

export const mockRentals: Rental[] = [
  {
    id: 'rent-001',
    equipmentId: 'eq-002',
    customerId: 'cus-001',
    startDate: pastDate(5).split('T')[0],
    endDate: pastDate(-2).split('T')[0],
    price: 150,
    status: 'active',
    notes: '周末露营使用',
    createdAt: pastDate(5),
  },
  {
    id: 'rent-002',
    equipmentId: 'eq-009',
    customerId: 'cus-003',
    startDate: pastDate(3).split('T')[0],
    endDate: pastDate(-1).split('T')[0],
    price: 120,
    status: 'active',
    notes: '家庭野餐',
    createdAt: pastDate(3),
  },
  {
    id: 'rent-003',
    equipmentId: 'eq-001',
    customerId: 'cus-002',
    startDate: pastDate(20).split('T')[0],
    endDate: pastDate(15).split('T')[0],
    price: 200,
    status: 'returned',
    notes: '五一假期露营',
    createdAt: pastDate(20),
  },
  {
    id: 'rent-004',
    equipmentId: 'eq-005',
    customerId: 'cus-005',
    startDate: pastDate(15).split('T')[0],
    endDate: pastDate(12).split('T')[0],
    price: 60,
    status: 'returned',
    notes: '登山活动',
    createdAt: pastDate(15),
  },
  {
    id: 'rent-005',
    equipmentId: 'eq-006',
    customerId: 'cus-001',
    startDate: pastDate(25).split('T')[0],
    endDate: pastDate(22).split('T')[0],
    price: 80,
    status: 'returned',
    notes: '',
    createdAt: pastDate(25),
  },
  {
    id: 'rent-006',
    equipmentId: 'eq-008',
    customerId: 'cus-004',
    startDate: pastDate(10).split('T')[0],
    endDate: pastDate(7).split('T')[0],
    price: 90,
    status: 'returned',
    notes: '生日聚会',
    createdAt: pastDate(10),
  },
];

export const mockDamageRecords: DamageRecord[] = [
  {
    id: 'dmg-001',
    equipmentId: 'eq-007',
    date: pastDate(2).split('T')[0],
    level: 'moderate',
    description: '灯珠部分不亮，疑似电池接触不良',
    reporter: '张管理员',
    status: 'reported',
    createdAt: pastDate(2),
  },
  {
    id: 'dmg-002',
    equipmentId: 'eq-004',
    date: pastDate(8).split('T')[0],
    level: 'minor',
    description: '肩带缝线轻微开线',
    reporter: '李操作员',
    status: 'repaired',
    createdAt: pastDate(8),
  },
  {
    id: 'dmg-003',
    equipmentId: 'eq-003',
    date: pastDate(15).split('T')[0],
    level: 'minor',
    description: '表面有轻微划痕',
    reporter: '张管理员',
    status: 'repaired',
    createdAt: pastDate(15),
  },
];

export const mockPartReplacements: PartReplacement[] = [
  {
    id: 'part-001',
    damageId: 'dmg-002',
    equipmentId: 'eq-004',
    partName: '加固缝线',
    quantity: 1,
    unitPrice: 30,
    createdAt: pastDate(6),
  },
  {
    id: 'part-002',
    damageId: 'dmg-003',
    equipmentId: 'eq-003',
    partName: '表面修复剂',
    quantity: 1,
    unitPrice: 25,
    createdAt: pastDate(13),
  },
];

export const mockMaintenances: Maintenance[] = [
  {
    id: 'mnt-001',
    equipmentId: 'eq-004',
    date: pastDate(6).split('T')[0],
    type: '配件更换',
    description: '肩带缝线加固',
    cost: 50,
    technician: '王师傅',
    status: 'completed',
    damageId: 'dmg-002',
    createdAt: pastDate(6),
  },
  {
    id: 'mnt-002',
    equipmentId: 'eq-003',
    date: pastDate(13).split('T')[0],
    type: '日常保养',
    description: '清洁和表面修复',
    cost: 45,
    technician: '李师傅',
    status: 'completed',
    damageId: 'dmg-003',
    createdAt: pastDate(13),
  },
  {
    id: 'mnt-003',
    equipmentId: 'eq-007',
    date: pastDate(1).split('T')[0],
    type: '故障维修',
    description: '灯珠更换和电路检修',
    cost: 80,
    technician: '张师傅',
    status: 'in_progress',
    damageId: 'dmg-001',
    createdAt: pastDate(1),
  },
];

export const mockInventoryChecks: InventoryCheck[] = [
  {
    id: 'inv-001',
    date: pastDate(30).split('T')[0],
    checker: '张管理员',
    status: 'completed',
    notes: '月底例行盘点，账实相符',
    createdAt: pastDate(30),
  },
  {
    id: 'inv-002',
    date: pastDate(60).split('T')[0],
    checker: '李管理员',
    status: 'completed',
    notes: '季度盘点',
    createdAt: pastDate(60),
  },
];

export const mockInventoryItems: InventoryItem[] = [
  {
    id: 'invitem-001',
    checkId: 'inv-001',
    equipmentId: 'eq-001',
    expectedStatus: 'available',
    actualStatus: 'available',
    difference: '正常',
    createdAt: pastDate(30),
  },
  {
    id: 'invitem-002',
    checkId: 'inv-001',
    equipmentId: 'eq-002',
    expectedStatus: 'available',
    actualStatus: 'available',
    difference: '正常',
    createdAt: pastDate(30),
  },
  {
    id: 'invitem-003',
    checkId: 'inv-001',
    equipmentId: 'eq-003',
    expectedStatus: 'available',
    actualStatus: 'available',
    difference: '正常',
    createdAt: pastDate(30),
  },
];
