import type {
  Equipment,
  Customer,
  Supplier,
  Rental,
  DamageRecord,
  PartReplacement,
  Maintenance,
  InventoryCheck,
  InventoryItem,
  DepositRule,
  PenaltyRule,
  DepositRecord,
  FinancialTransaction,
  RentalPenalty,
  DepositExemptCustomer,
} from '../types';

const now = new Date();
const pastDate = (days: number) => {
  const d = new Date(now);
  d.setDate(d.getDate() - days);
  return d.toISOString();
};

export const mockSuppliers: Supplier[] = [
  {
    id: 'sup-001',
    name: '山野户外用品有限公司',
    contact: '张经理',
    phone: '13800138001',
    address: '杭州市余杭区良渚街道',
    createdAt: pastDate(180),
  },
  {
    id: 'sup-002',
    name: '探险者装备科技',
    contact: '李总',
    phone: '13900139002',
    address: '宁波市鄞州区',
    createdAt: pastDate(150),
  },
  {
    id: 'sup-003',
    name: '自然风露营装备',
    contact: '王经理',
    phone: '13700137003',
    address: '温州市鹿城区',
    createdAt: pastDate(120),
  },
];

export const mockEquipments: Equipment[] = [
  {
    id: 'eq-001',
    equipmentNo: 'EQ-2024-001',
    name: '三人双层帐篷',
    category: '帐篷',
    brand: 'Naturehike',
    model: 'CloudUp 3',
    purchasePrice: 899,
    purchaseDate: pastDate(200).split('T')[0],
    status: 'available',
    location: 'A区-01货架',
    department: '户外装备部',
    custodian: '张管理员',
    usageCount: 15,
    supplierId: 'sup-001',
    notes: '防风防雨，适合3-4人使用',
    createdAt: pastDate(200),
    updatedAt: pastDate(5),
  },
  {
    id: 'eq-002',
    equipmentNo: 'EQ-2024-002',
    name: '羽绒睡袋',
    category: '睡袋',
    brand: '黑冰',
    model: 'B1000',
    purchasePrice: 659,
    purchaseDate: pastDate(180).split('T')[0],
    status: 'rented',
    location: 'B区-02货架',
    department: '户外装备部',
    custodian: '李操作员',
    usageCount: 23,
    supplierId: 'sup-002',
    notes: '舒适温度-10℃，填充白鸭绒',
    createdAt: pastDate(180),
    updatedAt: pastDate(2),
  },
  {
    id: 'eq-003',
    equipmentNo: 'EQ-2024-003',
    name: '自动充气防潮垫',
    category: '防潮垫',
    brand: '挪客',
    model: 'NH15Q001',
    purchasePrice: 299,
    purchaseDate: pastDate(160).split('T')[0],
    status: 'available',
    location: 'B区-05货架',
    department: '户外装备部',
    custodian: '张管理员',
    usageCount: 31,
    supplierId: 'sup-001',
    notes: '厚度5cm，自动充气',
    createdAt: pastDate(160),
    updatedAt: pastDate(10),
  },
  {
    id: 'eq-004',
    equipmentNo: 'EQ-2024-004',
    name: '60L登山包',
    category: '登山包',
    brand: 'Osprey',
    model: 'Kestrel 60',
    purchasePrice: 1299,
    purchaseDate: pastDate(140).split('T')[0],
    status: 'maintenance',
    location: 'C区-03货架',
    department: '登山装备部',
    custodian: '王师傅',
    usageCount: 18,
    supplierId: 'sup-003',
    notes: '背负系统舒适，大容量',
    createdAt: pastDate(140),
    updatedAt: pastDate(1),
  },
  {
    id: 'eq-005',
    equipmentNo: 'EQ-2024-005',
    name: '碳纤维登山杖',
    category: '登山杖',
    brand: '开拓者',
    model: '碳纤维T柄',
    purchasePrice: 199,
    purchaseDate: pastDate(120).split('T')[0],
    status: 'available',
    location: 'D区-01货架',
    department: '登山装备部',
    custodian: '李操作员',
    usageCount: 42,
    supplierId: 'sup-002',
    notes: '超轻碳纤维，三节可调',
    createdAt: pastDate(120),
    updatedAt: pastDate(7),
  },
  {
    id: 'eq-006',
    equipmentNo: 'EQ-2024-006',
    name: '便携卡式炉',
    category: '炉具',
    brand: '岩谷',
    model: 'CB-AS-1',
    purchasePrice: 259,
    purchaseDate: pastDate(100).split('T')[0],
    status: 'available',
    location: 'E区-02货架',
    department: '露营炊具部',
    custodian: '张管理员',
    usageCount: 27,
    supplierId: 'sup-001',
    notes: '防风设计，2.9kW火力',
    createdAt: pastDate(100),
    updatedAt: pastDate(3),
  },
  {
    id: 'eq-007',
    equipmentNo: 'EQ-2024-007',
    name: 'LED露营灯',
    category: '灯具',
    brand: 'Goal Zero',
    model: 'Lighthouse Micro',
    purchasePrice: 229,
    purchaseDate: pastDate(90).split('T')[0],
    status: 'damaged',
    location: '维修区',
    department: '照明设备部',
    custodian: '王师傅',
    usageCount: 35,
    supplierId: 'sup-003',
    notes: 'USB充电，多档亮度',
    createdAt: pastDate(90),
    updatedAt: pastDate(1),
  },
  {
    id: 'eq-008',
    equipmentNo: 'EQ-2024-008',
    name: '蛋卷桌',
    category: '桌椅',
    brand: '挪客',
    model: 'NH20JJ007',
    purchasePrice: 399,
    purchaseDate: pastDate(80).split('T')[0],
    status: 'available',
    location: 'F区-01货架',
    department: '露营家具部',
    custodian: '李操作员',
    usageCount: 19,
    supplierId: 'sup-002',
    notes: '榉木材质，折叠收纳',
    createdAt: pastDate(80),
    updatedAt: pastDate(4),
  },
  {
    id: 'eq-009',
    equipmentNo: 'EQ-2024-009',
    name: '六角天幕',
    category: '天幕',
    brand: '牧高笛',
    model: 'NXVQU61001',
    purchasePrice: 599,
    purchaseDate: pastDate(70).split('T')[0],
    status: 'rented',
    location: 'G区-02货架',
    department: '户外装备部',
    custodian: '张管理员',
    usageCount: 12,
    supplierId: 'sup-001',
    notes: '银胶涂层，防晒防雨',
    createdAt: pastDate(70),
    updatedAt: pastDate(2),
  },
  {
    id: 'eq-010',
    equipmentNo: 'EQ-2024-010',
    name: '折叠月亮椅',
    category: '桌椅',
    brand: '牧高笛',
    model: 'NX23665005',
    purchasePrice: 269,
    purchaseDate: pastDate(60).split('T')[0],
    status: 'available',
    location: 'F区-03货架',
    department: '露营家具部',
    custodian: '王师傅',
    usageCount: 28,
    supplierId: 'sup-003',
    notes: '人体工学设计，快速折叠',
    createdAt: pastDate(60),
    updatedAt: pastDate(5),
  },
  {
    id: 'eq-011',
    equipmentNo: 'EQ-2023-011',
    name: '老式双人帐篷',
    category: '帐篷',
    brand: '骆驼',
    model: 'Classic 2',
    purchasePrice: 499,
    purchaseDate: pastDate(500).split('T')[0],
    status: 'scrapped',
    location: '报废区',
    department: '户外装备部',
    custodian: '张管理员',
    usageCount: 68,
    supplierId: 'sup-001',
    notes: '已报废，帐杆断裂多次修复',
    createdAt: pastDate(500),
    updatedAt: pastDate(30),
  },
  {
    id: 'eq-012',
    equipmentNo: 'EQ-2023-012',
    name: '旧款棉睡袋',
    category: '睡袋',
    brand: '天石',
    model: 'Cotton-200',
    purchasePrice: 199,
    purchaseDate: pastDate(400).split('T')[0],
    status: 'decommissioned',
    location: '停用区',
    department: '户外装备部',
    custodian: '李操作员',
    usageCount: 52,
    supplierId: 'sup-002',
    notes: '已停用，保暖效果下降',
    createdAt: pastDate(400),
    updatedAt: pastDate(45),
  },
];

export const mockCustomers: Customer[] = [
  {
    id: 'cus-001',
    name: '陈小明',
    phone: '13812345678',
    idCard: '330100199001011234',
    address: '杭州市西湖区',
    rentalCount: 5,
    createdAt: pastDate(150),
  },
  {
    id: 'cus-002',
    name: '李雪梅',
    phone: '13923456789',
    idCard: '330200199203152345',
    address: '杭州市拱墅区',
    rentalCount: 3,
    createdAt: pastDate(120),
  },
  {
    id: 'cus-003',
    name: '王大伟',
    phone: '13734567890',
    idCard: '330300198805203456',
    address: '杭州市余杭区',
    rentalCount: 8,
    createdAt: pastDate(100),
  },
  {
    id: 'cus-004',
    name: '张晓燕',
    phone: '13645678901',
    idCard: '330400199508084567',
    address: '杭州市滨江区',
    rentalCount: 2,
    createdAt: pastDate(80),
  },
  {
    id: 'cus-005',
    name: '刘强',
    phone: '13556789012',
    idCard: '330500198712125678',
    address: '杭州市萧山区',
    rentalCount: 6,
    createdAt: pastDate(60),
  },
];

export const mockRentals: Rental[] = [
  {
    id: 'rent-001',
    equipmentId: 'eq-002',
    customerId: 'cus-001',
    startDate: pastDate(5).split('T')[0],
    endDate: pastDate(-2).split('T')[0],
    price: 150,
    status: 'active',
    channel: 'individual',
    notes: '周末露营使用',
    createdAt: pastDate(5),
  },
  {
    id: 'rent-002',
    equipmentId: 'eq-009',
    customerId: 'cus-003',
    startDate: pastDate(3).split('T')[0],
    endDate: pastDate(-1).split('T')[0],
    price: 120,
    status: 'active',
    channel: 'group',
    notes: '公司团建活动',
    createdAt: pastDate(3),
  },
  {
    id: 'rent-003',
    equipmentId: 'eq-001',
    customerId: 'cus-002',
    startDate: pastDate(20).split('T')[0],
    endDate: pastDate(15).split('T')[0],
    price: 200,
    status: 'returned',
    channel: 'online',
    notes: '五一假期露营 - 线上预订',
    createdAt: pastDate(20),
  },
  {
    id: 'rent-004',
    equipmentId: 'eq-005',
    customerId: 'cus-005',
    startDate: pastDate(15).split('T')[0],
    endDate: pastDate(12).split('T')[0],
    price: 60,
    status: 'returned',
    channel: 'individual',
    notes: '登山活动',
    createdAt: pastDate(15),
  },
  {
    id: 'rent-005',
    equipmentId: 'eq-006',
    customerId: 'cus-001',
    startDate: pastDate(25).split('T')[0],
    endDate: pastDate(22).split('T')[0],
    price: 80,
    status: 'returned',
    channel: 'online',
    notes: '线上小程序预订',
    createdAt: pastDate(25),
  },
  {
    id: 'rent-006',
    equipmentId: 'eq-008',
    customerId: 'cus-004',
    startDate: pastDate(10).split('T')[0],
    endDate: pastDate(7).split('T')[0],
    price: 90,
    status: 'returned',
    channel: 'group',
    notes: '部门团建生日聚会',
    createdAt: pastDate(10),
  },
];

export const mockDamageRecords: DamageRecord[] = [
  {
    id: 'dmg-001',
    equipmentId: 'eq-007',
    date: pastDate(2).split('T')[0],
    level: 'moderate',
    description: '灯珠部分不亮，疑似电池接触不良',
    reporter: '张管理员',
    status: 'reported',
    photoUrls: [],
    createdAt: pastDate(2),
  },
  {
    id: 'dmg-002',
    equipmentId: 'eq-004',
    date: pastDate(8).split('T')[0],
    level: 'minor',
    description: '肩带缝线轻微开线',
    reporter: '李操作员',
    status: 'repaired',
    photoUrls: [],
    createdAt: pastDate(8),
  },
  {
    id: 'dmg-003',
    equipmentId: 'eq-003',
    date: pastDate(15).split('T')[0],
    level: 'minor',
    description: '表面有轻微划痕',
    reporter: '张管理员',
    status: 'repaired',
    photoUrls: [],
    createdAt: pastDate(15),
  },
];

export const mockPartReplacements: PartReplacement[] = [
  {
    id: 'part-001',
    damageId: 'dmg-002',
    equipmentId: 'eq-004',
    partName: '加固缝线',
    quantity: 1,
    unitPrice: 30,
    createdAt: pastDate(6),
  },
  {
    id: 'part-002',
    damageId: 'dmg-003',
    equipmentId: 'eq-003',
    partName: '表面修复剂',
    quantity: 1,
    unitPrice: 25,
    createdAt: pastDate(13),
  },
];

export const mockMaintenances: Maintenance[] = [
  {
    id: 'mnt-001',
    equipmentId: 'eq-004',
    date: pastDate(6).split('T')[0],
    type: '配件更换',
    description: '肩带缝线加固',
    cost: 50,
    technician: '王师傅',
    status: 'completed',
    damageId: 'dmg-002',
    createdAt: pastDate(6),
  },
  {
    id: 'mnt-002',
    equipmentId: 'eq-003',
    date: pastDate(13).split('T')[0],
    type: '日常保养',
    description: '清洁和表面修复',
    cost: 45,
    technician: '李师傅',
    status: 'completed',
    damageId: 'dmg-003',
    createdAt: pastDate(13),
  },
  {
    id: 'mnt-003',
    equipmentId: 'eq-007',
    date: pastDate(1).split('T')[0],
    type: '故障维修',
    description: '灯珠更换和电路检修',
    cost: 80,
    technician: '张师傅',
    status: 'in_progress',
    damageId: 'dmg-001',
    createdAt: pastDate(1),
  },
];

export const mockInventoryChecks: InventoryCheck[] = [
  {
    id: 'inv-001',
    date: pastDate(30).split('T')[0],
    checker: '张管理员',
    status: 'completed',
    notes: '月底例行盘点，账实相符',
    createdAt: pastDate(30),
  },
  {
    id: 'inv-002',
    date: pastDate(60).split('T')[0],
    checker: '李管理员',
    status: 'completed',
    notes: '季度盘点',
    createdAt: pastDate(60),
  },
];

export const mockInventoryItems: InventoryItem[] = [
  {
    id: 'invitem-001',
    checkId: 'inv-001',
    equipmentId: 'eq-001',
    expectedStatus: 'available',
    actualStatus: 'available',
    difference: '正常',
    createdAt: pastDate(30),
  },
  {
    id: 'invitem-002',
    checkId: 'inv-001',
    equipmentId: 'eq-002',
    expectedStatus: 'available',
    actualStatus: 'available',
    difference: '正常',
    createdAt: pastDate(30),
  },
  {
    id: 'invitem-003',
    checkId: 'inv-001',
    equipmentId: 'eq-003',
    expectedStatus: 'available',
    actualStatus: 'available',
    difference: '正常',
    createdAt: pastDate(30),
  },
];

export const mockDepositRules: DepositRule[] = [
  {
    id: 'dep-rule-001',
    name: '帐篷类基础押金',
    type: 'category',
    category: '帐篷',
    depositAmount: 300,
    isActive: true,
    createdAt: pastDate(200),
    updatedAt: pastDate(200),
  },
  {
    id: 'dep-rule-002',
    name: '睡袋类基础押金',
    type: 'category',
    category: '睡袋',
    depositAmount: 200,
    isActive: true,
    createdAt: pastDate(190),
    updatedAt: pastDate(190),
  },
  {
    id: 'dep-rule-003',
    name: '登山包类基础押金',
    type: 'category',
    category: '登山包',
    depositAmount: 400,
    isActive: true,
    createdAt: pastDate(180),
    updatedAt: pastDate(180),
  },
  {
    id: 'dep-rule-004',
    name: '炉具类基础押金',
    type: 'category',
    category: '炉具',
    depositAmount: 100,
    isActive: true,
    createdAt: pastDate(170),
    updatedAt: pastDate(170),
  },
  {
    id: 'dep-rule-005',
    name: '桌椅类基础押金',
    type: 'category',
    category: '桌椅',
    depositAmount: 150,
    isActive: true,
    createdAt: pastDate(160),
    updatedAt: pastDate(160),
  },
  {
    id: 'dep-rule-006',
    name: '天幕类基础押金',
    type: 'category',
    category: '天幕',
    depositAmount: 200,
    isActive: true,
    createdAt: pastDate(150),
    updatedAt: pastDate(150),
  },
  {
    id: 'dep-rule-007',
    name: 'Osprey 60L登山包高额押金',
    type: 'equipment',
    equipmentId: 'eq-004',
    depositAmount: 600,
    isActive: true,
    createdAt: pastDate(140),
    updatedAt: pastDate(140),
  },
  {
    id: 'dep-rule-008',
    name: '三人双层帐篷押金',
    type: 'equipment',
    equipmentId: 'eq-001',
    depositAmount: 350,
    isActive: true,
    createdAt: pastDate(130),
    updatedAt: pastDate(130),
  },
  {
    id: 'dep-rule-009',
    name: '防潮垫类基础押金',
    type: 'category',
    category: '防潮垫',
    depositAmount: 100,
    isActive: true,
    createdAt: pastDate(120),
    updatedAt: pastDate(120),
  },
  {
    id: 'dep-rule-010',
    name: '登山杖类基础押金',
    type: 'category',
    category: '登山杖',
    depositAmount: 50,
    isActive: true,
    createdAt: pastDate(110),
    updatedAt: pastDate(110),
  },
  {
    id: 'dep-rule-011',
    name: '灯具类基础押金',
    type: 'category',
    category: '灯具',
    depositAmount: 80,
    isActive: true,
    createdAt: pastDate(100),
    updatedAt: pastDate(100),
  },
];

export const mockPenaltyRules: PenaltyRule[] = [
  {
    id: 'pen-rule-001',
    name: '普通装备违约金倍率',
    valueLevel: 'normal',
    dailyRateMultiplier: 1.5,
    isActive: true,
    createdAt: pastDate(200),
    updatedAt: pastDate(200),
  },
  {
    id: 'pen-rule-002',
    name: '高价值装备违约金倍率',
    valueLevel: 'high',
    dailyRateMultiplier: 2.0,
    isActive: true,
    createdAt: pastDate(200),
    updatedAt: pastDate(200),
  },
];

export const mockDepositExemptCustomers: DepositExemptCustomer[] = [
  {
    id: 'exempt-001',
    customerId: 'cus-003',
    reason: 'VIP会员，免押金',
    minRentalCount: 5,
    isActive: true,
    createdAt: pastDate(100),
    updatedAt: pastDate(50),
  },
  {
    id: 'exempt-002',
    customerId: 'cus-001',
    reason: '高复购客户，累计租赁超10次',
    minRentalCount: 10,
    isActive: true,
    createdAt: pastDate(80),
    updatedAt: pastDate(30),
  },
];

export const mockDepositRecords: DepositRecord[] = [
  {
    id: 'dep-001',
    rentalId: 'rent-001',
    customerId: 'cus-001',
    equipmentId: 'eq-002',
    totalDepositAmount: 200,
    collectedAmount: 200,
    refundedAmount: 0,
    forfeitedAmount: 0,
    status: 'collected',
    isExempt: false,
    createdAt: pastDate(5),
    updatedAt: pastDate(5),
  },
  {
    id: 'dep-002',
    rentalId: 'rent-002',
    customerId: 'cus-003',
    equipmentId: 'eq-009',
    totalDepositAmount: 200,
    collectedAmount: 0,
    refundedAmount: 0,
    forfeitedAmount: 0,
    status: 'pending',
    isExempt: true,
    exemptReason: 'VIP会员，免押金',
    createdAt: pastDate(3),
    updatedAt: pastDate(3),
  },
  {
    id: 'dep-003',
    rentalId: 'rent-003',
    customerId: 'cus-002',
    equipmentId: 'eq-001',
    totalDepositAmount: 350,
    collectedAmount: 350,
    refundedAmount: 350,
    forfeitedAmount: 0,
    status: 'refunded_full',
    isExempt: false,
    createdAt: pastDate(20),
    updatedAt: pastDate(15),
  },
  {
    id: 'dep-004',
    rentalId: 'rent-004',
    customerId: 'cus-005',
    equipmentId: 'eq-005',
    totalDepositAmount: 50,
    collectedAmount: 50,
    refundedAmount: 50,
    forfeitedAmount: 0,
    status: 'refunded_full',
    isExempt: false,
    createdAt: pastDate(15),
    updatedAt: pastDate(12),
  },
  {
    id: 'dep-005',
    rentalId: 'rent-005',
    customerId: 'cus-001',
    equipmentId: 'eq-006',
    totalDepositAmount: 100,
    collectedAmount: 100,
    refundedAmount: 100,
    forfeitedAmount: 0,
    status: 'refunded_full',
    isExempt: false,
    createdAt: pastDate(25),
    updatedAt: pastDate(22),
  },
  {
    id: 'dep-006',
    rentalId: 'rent-006',
    customerId: 'cus-004',
    equipmentId: 'eq-008',
    totalDepositAmount: 150,
    collectedAmount: 150,
    refundedAmount: 150,
    forfeitedAmount: 0,
    status: 'refunded_full',
    isExempt: false,
    createdAt: pastDate(10),
    updatedAt: pastDate(7),
  },
];

export const mockFinancialTransactions: FinancialTransaction[] = [
  {
    id: 'trans-001',
    rentalId: 'rent-001',
    customerId: 'cus-001',
    type: 'deposit_collect',
    amount: 200,
    direction: 'income',
    description: '收取羽绒睡袋押金',
    operator: '张管理员',
    createdAt: pastDate(5),
  },
  {
    id: 'trans-002',
    rentalId: 'rent-003',
    customerId: 'cus-002',
    type: 'deposit_collect',
    amount: 350,
    direction: 'income',
    description: '收取三人双层帐篷押金',
    operator: '张管理员',
    createdAt: pastDate(20),
  },
  {
    id: 'trans-003',
    rentalId: 'rent-003',
    customerId: 'cus-002',
    type: 'deposit_refund',
    amount: 350,
    direction: 'expense',
    description: '全额退还三人双层帐篷押金',
    operator: '李管理员',
    createdAt: pastDate(15),
  },
  {
    id: 'trans-004',
    rentalId: 'rent-004',
    customerId: 'cus-005',
    type: 'deposit_collect',
    amount: 50,
    direction: 'income',
    description: '收取登山杖押金',
    operator: '张管理员',
    createdAt: pastDate(15),
  },
  {
    id: 'trans-005',
    rentalId: 'rent-004',
    customerId: 'cus-005',
    type: 'deposit_refund',
    amount: 50,
    direction: 'expense',
    description: '全额退还登山杖押金',
    operator: '李管理员',
    createdAt: pastDate(12),
  },
  {
    id: 'trans-006',
    rentalId: 'rent-005',
    customerId: 'cus-001',
    type: 'deposit_collect',
    amount: 100,
    direction: 'income',
    description: '收取卡式炉押金',
    operator: '张管理员',
    createdAt: pastDate(25),
  },
  {
    id: 'trans-007',
    rentalId: 'rent-005',
    customerId: 'cus-001',
    type: 'deposit_refund',
    amount: 100,
    direction: 'expense',
    description: '全额退还卡式炉押金',
    operator: '李管理员',
    createdAt: pastDate(22),
  },
  {
    id: 'trans-008',
    rentalId: 'rent-006',
    customerId: 'cus-004',
    type: 'deposit_collect',
    amount: 150,
    direction: 'income',
    description: '收取蛋卷桌押金',
    operator: '张管理员',
    createdAt: pastDate(10),
  },
  {
    id: 'trans-009',
    rentalId: 'rent-006',
    customerId: 'cus-004',
    type: 'deposit_refund',
    amount: 150,
    direction: 'expense',
    description: '全额退还蛋卷桌押金',
    operator: '李管理员',
    createdAt: pastDate(7),
  },
];

export const mockRentalPenalties: RentalPenalty[] = [];
