import type { Field } from './types';

export const DIMENSION_FIELDS: Field[] = [
  {
    id: 'category',
    name: '装备分类',
    type: 'dimension',
    dataType: 'string',
    source: 'equipment',
    description: '装备所属的分类',
  },
  {
    id: 'equipmentName',
    name: '装备名称',
    type: 'dimension',
    dataType: 'string',
    source: 'equipment',
    description: '装备的名称',
  },
  {
    id: 'brand',
    name: '品牌',
    type: 'dimension',
    dataType: 'string',
    source: 'equipment',
    description: '装备品牌',
  },
  {
    id: 'status',
    name: '装备状态',
    type: 'dimension',
    dataType: 'string',
    source: 'equipment',
    description: '装备当前状态',
  },
  {
    id: 'location',
    name: '存放位置',
    type: 'dimension',
    dataType: 'string',
    source: 'equipment',
    description: '装备存放位置',
  },
  {
    id: 'customerName',
    name: '客户名称',
    type: 'dimension',
    dataType: 'string',
    source: 'customer',
    description: '客户姓名',
  },
  {
    id: 'customerType',
    name: '客户类型',
    type: 'dimension',
    dataType: 'string',
    source: 'customer',
    description: '根据租赁次数划分的客户类型',
  },
  {
    id: 'rentalStatus',
    name: '租赁状态',
    type: 'dimension',
    dataType: 'string',
    source: 'rental',
    description: '租赁订单状态',
  },
  {
    id: 'month',
    name: '月份',
    type: 'dimension',
    dataType: 'date',
    source: 'rental',
    description: '租赁月份',
  },
  {
    id: 'quarter',
    name: '季度',
    type: 'dimension',
    dataType: 'date',
    source: 'rental',
    description: '租赁季度',
  },
  {
    id: 'year',
    name: '年份',
    type: 'dimension',
    dataType: 'date',
    source: 'rental',
    description: '租赁年份',
  },
  {
    id: 'supplierName',
    name: '供应商名称',
    type: 'dimension',
    dataType: 'string',
    source: 'supplier',
    description: '供应商名称',
  },
  {
    id: 'damageLevel',
    name: '损耗等级',
    type: 'dimension',
    dataType: 'string',
    source: 'damage',
    description: '损耗严重程度',
  },
  {
    id: 'maintenanceType',
    name: '维护类型',
    type: 'dimension',
    dataType: 'string',
    source: 'maintenance',
    description: '维护保养类型',
  },
  {
    id: 'packageType',
    name: '租赁套餐',
    type: 'dimension',
    dataType: 'string',
    source: 'rental',
    description: '根据租赁价格划分的套餐类型',
  },
];

export const MEASURE_FIELDS: Field[] = [
  {
    id: 'usageCount',
    name: '使用次数',
    type: 'measure',
    dataType: 'number',
    source: 'equipment',
    description: '装备累计使用次数',
  },
  {
    id: 'rentalCount',
    name: '租赁次数',
    type: 'measure',
    dataType: 'number',
    source: 'rental',
    description: '租赁订单数量',
  },
  {
    id: 'rentalRevenue',
    name: '租赁收入',
    type: 'measure',
    dataType: 'number',
    source: 'rental',
    description: '租赁收入金额',
  },
  {
    id: 'purchasePrice',
    name: '采购成本',
    type: 'measure',
    dataType: 'number',
    source: 'equipment',
    description: '装备采购价格',
  },
  {
    id: 'equipmentCount',
    name: '装备数量',
    type: 'measure',
    dataType: 'number',
    source: 'equipment',
    description: '装备数量统计',
  },
  {
    id: 'customerCount',
    name: '客户数量',
    type: 'measure',
    dataType: 'number',
    source: 'customer',
    description: '客户数量统计',
  },
  {
    id: 'avgRentalPrice',
    name: '平均租赁价格',
    type: 'measure',
    dataType: 'number',
    source: 'rental',
    description: '平均每次租赁价格',
  },
  {
    id: 'totalRevenue',
    name: '累计收入',
    type: 'measure',
    dataType: 'number',
    source: 'rental',
    description: '装备累计租赁收入',
  },
  {
    id: 'damageCount',
    name: '损耗次数',
    type: 'measure',
    dataType: 'number',
    source: 'damage',
    description: '损耗记录数量',
  },
  {
    id: 'maintenanceCost',
    name: '维护费用',
    type: 'measure',
    dataType: 'number',
    source: 'maintenance',
    description: '维护保养费用',
  },
  {
    id: 'maintenanceCount',
    name: '维护次数',
    type: 'measure',
    dataType: 'number',
    source: 'maintenance',
    description: '维护保养次数',
  },
  {
    id: 'roi',
    name: '投资回报率',
    type: 'measure',
    dataType: 'number',
    source: 'equipment',
    description: '装备投资回报率(累计收入/采购成本)',
  },
];

export const ALL_FIELDS: Field[] = [...DIMENSION_FIELDS, ...MEASURE_FIELDS];

export const getFieldById = (id: string): Field | undefined => {
  return ALL_FIELDS.find((f) => f.id === id);
};

export const getFieldsBySource = (source: string): Field[] => {
  return ALL_FIELDS.filter((f) => f.source === source);
};
